### ISSUE TITLE
Chronos App

### ISSUE THREAD

**Issue by FutureCow** [fbiego/ESP32_OLED_BLE#2]
Will this project also work with your new Chronos App, instead of the DT78 Android App?

**Comment by fbiego** [comment]
It is possible, the code has to be rewritten to use the [`Chronos-ESP32 library`](https://github.com/fbiego/chronos-esp32)

**Comment by fbiego** [comment]
The code has been rewritten to use the [Chronos-ESP32 library](https://github.com/fbiego/chronos-esp32)
